name: hypercap-trial-ae
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyter
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - openpyxl
  - pip
  - pip:
      - requests
      - scikit-learn
